// Fill out your copyright notice in the Description page of Project Settings.


#include "Inventory/UI/Items/ToolTip/ItemToolTipWidget.h"

#include "Components/Border.h"
#include "Components/HorizontalBox.h"
#include "Components/Image.h"
#include "Components/TextBlock.h"
#include "Components/UniformGridPanel.h"
#include "Components/UniformGridSlot.h"
#include "Components/VerticalBox.h"
#include "Components/VerticalBoxSlot.h"
#include "Components/Status/StatsComponent.h"
#include "Interface/ComponentManager.h"
#include "Inventory/Components/EquipmentComponent.h"
#include "Inventory/FunctionLibrary/InventoryUtilityLibrary.h"
#include "Inventory/UI/Common/ItemStatsSlotWidget.h"

void UItemToolTipWidget::NativeConstruct()
{
	Super::NativeConstruct();
	
	APlayerController* LocalPC = GetOwningPlayer();
	
	if(LocalPC)
	{
		if(IComponentManager* ComponentManager = Cast<IComponentManager>(LocalPC))
		{
			PlayerEquipment = ComponentManager->GetEquipmentComponent();
		}
	}
	if(UInventoryUtilityLibrary::IsItemClassValid(ItemData))
	{
		SetVisibility(bIsCompareItem ? ESlateVisibility::SelfHitTestInvisible : ESlateVisibility::Hidden);
		OnPlayAnimation();
		SetItemInfo();
	}
	else
	{
		SetVisibility(ESlateVisibility::Hidden);
	}
}

void UItemToolTipWidget::SetItemInfo()
{
	SetItemName();
	SetItemType();
	SetItemRarity();
	SetItemDescription();
	SetItemRarityColor();
	BuildItemStats();
	SetItemWeight();
	SetItemValue();
	SetItemRequiredLevel();
	SetItemRequiredLevelColor();
	SetItemDurability();
	SetItemDurabilityColor();
	SetAlreadyReadVisibility();
}

void UItemToolTipWidget::ShowComparisonToolTip()
{
	APlayerController* LocalPC = GetOwningPlayer();
	if(!LocalPC)
	{
		return;
	}
	
	FItemData LocalSlotData;
	if(!ComparisonToolTipWidget && PlayerEquipment->GetItemByEquipmentSlot(ItemData.EquipmentSlot,LocalSlotData))
	{
		ComparisonToolTipWidget = CreateWidget<UItemToolTipWidget>(LocalPC,ItemToolTipWidgetClass);
		if(ComparisonToolTipWidget)
		{
			ComparisonToolTipWidget->ItemData = LocalSlotData;
			ComparisonToolTipWidget->bIsCompareItem = true;
		}
		if(UniformGridPanel_Component)
		{
			UUniformGridSlot* LocalGridSlot = UniformGridPanel_Component->AddChildToUniformGrid(ComparisonToolTipWidget,0,0);
			LocalGridSlot->SetColumn(-1); // Position on the left side
			LocalGridSlot->SetHorizontalAlignment(HAlign_Right);
			// Update Compared Values in THIS widget
			UpdateItemStatsComparison(ComparisonToolTipWidget);
			// Update Compared Values in COMPARED widget
			ComparisonToolTipWidget->UpdateItemStatsComparison(this);
		}
	}
}

void UItemToolTipWidget::HideComparisonToolTip()
{
	if(ComparisonToolTipWidget)
	{
		ComparisonToolTipWidget->RemoveFromParent();
		ComparisonToolTipWidget = nullptr;
		UpdateItemStatsComparison(nullptr);
	}
}

void UItemToolTipWidget::SetItemImageAsync()
{
	UItemBase* ItemBase = ItemData.ItemClass.GetDefaultObject();
	if(!ItemBase && ItemBase->Image.IsNull())
	{
		return;
	}

	// 2. ìŠ¤íŠ¸ë¦¬ë° ê´€ë¦¬ìë¥¼ í†µí•´ ë¹„ë™ê¸° ë¡œë”©ì„ ìš”ì²­í•©ë‹ˆë‹¤.
	// UAssetManager::GetStreamableManager()ëŠ” ì—ì…‹ì„ ê´€ë¦¬í•˜ëŠ” ì‹±ê¸€í†¤ ê°ì²´ë¥¼ ê°€ì ¸ì˜µë‹ˆë‹¤.
	FStreamableManager& StreamableManager = UAssetManager::Get().GetStreamableManager();
    
	// RequestAsyncLoad í•¨ìˆ˜ì— ë¡œë“œí•  ì—ì…‹ ê²½ë¡œì™€, ë¡œë“œê°€ ì™„ë£Œë˜ë©´ ì‹¤í–‰í•  ëŒë‹¤ í•¨ìˆ˜ë¥¼ ì „ë‹¬í•©ë‹ˆë‹¤.
	StreamableManager.RequestAsyncLoad(ItemBase->Image.ToSoftObjectPath(), 
		// [this]ëŠ” ì´ ëŒë‹¤ í•¨ìˆ˜ê°€ í´ë˜ìŠ¤ ë©¤ë²„(ItemImage)ì— ì ‘ê·¼í•  ìˆ˜ ìˆê²Œ í•©ë‹ˆë‹¤.
		[this, ItemBase]() 
		{
			// ğŸ’¡ ì´ ëŒë‹¤ í•¨ìˆ˜ ë‚´ë¶€ê°€ ë¸”ë£¨í”„ë¦°íŠ¸ì˜ 'Completed' í•€ ë’¤ì— ì—°ê²°ëœ ë¡œì§ê³¼ ê°™ìŠµë‹ˆë‹¤.

			// 3. ë¡œë”©ì´ ì™„ë£Œë˜ë©´, í•´ë‹¹ ì—ì…‹ì„ ê°€ì ¸ì™€ì„œ ì´ë¯¸ì§€ ìœ„ì ¯ì— ì ìš©í•©ë‹ˆë‹¤.
			// ìœ„ì ¯ì´ íŒŒê´´ë˜ì—ˆì„ ìˆ˜ë„ ìˆìœ¼ë¯€ë¡œ IsValid ì²´í¬ë¥¼ í•˜ëŠ” ê²ƒì´ ì•ˆì „í•©ë‹ˆë‹¤.
			if (IsValid(this) && IsValid(Image_Item))
			{
				// Get() í•¨ìˆ˜ë¡œ ì‹¤ì œ UTexture2D* ê°ì²´ë¥¼ ê°€ì ¸ì˜µë‹ˆë‹¤.
				UTexture2D* LoadedTexture = Cast<UTexture2D>(ItemBase->Image.Get());
				if (LoadedTexture)
				{
					Image_Item->SetBrushFromTexture(LoadedTexture);
				}
			}
		}
	);
}

void UItemToolTipWidget::BuildItemStats()
{
	APlayerController* LocalPC = GetOwningPlayer();
	if(!UInventoryUtilityLibrary::IsItemClassValid(ItemData) || !ItemStatsSlotWidgetClass || !LocalPC)
	{ 
		return;
	}
	UItemBase* ItemBase = Cast<UItemBase>(ItemData.ItemClass->GetDefaultObject());
	
	if (!ItemBase) 
	{
		return;
	}
	StatWidgets.Empty();
	VerticalBox_ItemStats->ClearChildren();

	for(const auto& ItemStatRow : ItemBase->Stats)
	{
		UItemStatsSlotWidget* LocalItemStatsSlotWidget = CreateWidget<UItemStatsSlotWidget>(LocalPC,ItemStatsSlotWidgetClass);
		if(LocalItemStatsSlotWidget)
		{
			LocalItemStatsSlotWidget->StatName = FText::FromString(ItemStatRow.StatTag.ToString());
			LocalItemStatsSlotWidget->StatValue = ItemStatRow.Value;
			StatWidgets.Add(ItemStatRow.StatTag.ToString(),LocalItemStatsSlotWidget);

			UVerticalBoxSlot* LocalVerticalBoxSlot = VerticalBox_ItemStats->AddChildToVerticalBox(LocalItemStatsSlotWidget);
			LocalVerticalBoxSlot->SetHorizontalAlignment(HAlign_Fill);
		}
	}
}

void UItemToolTipWidget::SetItemName()
{
	if(UInventoryUtilityLibrary::IsItemClassValid(ItemData))
	{
		UItemBase* ItemBase = ItemData.ItemClass.GetDefaultObject();
		TextBlock_ItemName->SetText(ItemBase->Name);
	}
}

void UItemToolTipWidget::SetItemType()
{
	if(UInventoryUtilityLibrary::IsItemClassValid(ItemData))
	{
		UItemBase* ItemBase = ItemData.ItemClass.GetDefaultObject();
		
		const UEnum* TypeEnum = FindObject<UEnum>(ANY_PACKAGE, TEXT("EItemType"), true);
		if(TypeEnum)
		{
			FName EnumName = TypeEnum->GetNameByValue((int64)ItemBase->Type);
			TextBlock_ItemType->SetText(FText::FromName(EnumName));	
		}
	}
}

void UItemToolTipWidget::SetItemRarity()
{
	if(UInventoryUtilityLibrary::IsItemClassValid(ItemData))
	{
		UItemBase* ItemBase = ItemData.ItemClass.GetDefaultObject();
		
		const UEnum* TypeEnum = FindObject<UEnum>(ANY_PACKAGE, TEXT("EItemRarity"), true);
		if(TypeEnum)
		{
			FName EnumName = TypeEnum->GetNameByValue((int64)ItemBase->Rarity);
			TextBlock_ItemRarity->SetText(FText::FromName(EnumName));	
		}
	}
}

void UItemToolTipWidget::SetItemRarityColor()
{
	if(UInventoryUtilityLibrary::IsItemClassValid(ItemData))
	{
		UItemBase* ItemBase = ItemData.ItemClass.GetDefaultObject();
		FLinearColor RarityLinearColor = UInventoryUtilityLibrary::GetRarityColor(ItemBase->Rarity).GetSpecifiedColor();
		Border_ItemInfo->SetContentColorAndOpacity(RarityLinearColor);
		Border_ItemInfo->SetBrushColor(RarityLinearColor);
	}
}

void UItemToolTipWidget::SetItemDescription()
{
	if(UInventoryUtilityLibrary::IsItemClassValid(ItemData))
	{
		UItemBase* ItemBase = ItemData.ItemClass.GetDefaultObject();
		FText ItemDescription = ItemBase->Description;
		if(ItemDescription.IsEmpty())
		{
			TextBlock_Description->SetVisibility(ESlateVisibility::Collapsed);
		}
		else
		{
			TextBlock_Description->SetVisibility(ESlateVisibility::SelfHitTestInvisible);
			TextBlock_Description->SetText(ItemDescription);
		}
	}
}

void UItemToolTipWidget::SetItemWeight()
{
	// Weight 
}

void UItemToolTipWidget::SetItemValue()
{
	// Value
}

void UItemToolTipWidget::SetItemRequiredLevel()
{
	if(UInventoryUtilityLibrary::IsItemClassValid(ItemData))
	{
		UItemBase* ItemBase = ItemData.ItemClass.GetDefaultObject();
		if(ItemBase->RequiredLevel > 0)
		{
			HorizontalBox_RequiredLevel->SetVisibility(ESlateVisibility::SelfHitTestInvisible);
			TextBlock_RequiredLevel->SetText(FText::AsNumber(ItemBase->RequiredLevel));
		}
		else
		{
			HorizontalBox_RequiredLevel->SetVisibility(ESlateVisibility::Collapsed);
		}
	}
}

void UItemToolTipWidget::SetItemRequiredLevelColor()
{
	APlayerController* LocalPC = GetOwningPlayer();
	if(UInventoryUtilityLibrary::IsItemClassValid(ItemData) || LocalPC)
	{
		IComponentManager* ComponentManager = Cast<IComponentManager>(LocalPC);
		if(ComponentManager)
		{
			UStatsComponent* StatsComponent = ComponentManager->GetStatsComponent();
			if(StatsComponent)
			{
				UItemBase* ItemBase = ItemData.ItemClass.GetDefaultObject();
				// if(StatsComponent->CurrentLevel >= ItemBase->RequiredLevel)
				// {
				// 	TextBlock_RequiredLevel->SetColorAndOpacity(TextGreenColor);
				// 	TextBlock_RequiredLevelText->SetColorAndOpacity(TextGreenColor);
				// }
				// else
				// {
				// 	TextBlock_RequiredLevel->SetColorAndOpacity(TextRedColor);
				// 	TextBlock_RequiredLevelText->SetColorAndOpacity(TextRedColor);
				// }
			}
		}
	}
}

void UItemToolTipWidget::SetItemDurability()
{
	if(UInventoryUtilityLibrary::IsItemClassValid(ItemData))
	{
		UItemBase* ItemBase = ItemData.ItemClass.GetDefaultObject();
		if(ItemBase->UseDurability)
		{
			HorizontalBox_Durability->SetVisibility(ESlateVisibility::SelfHitTestInvisible);

			const int32 DurabilityValue = ItemData.Durability;
			FFormatOrderedArguments Args;
			Args.Add(FText::AsNumber(DurabilityValue));
			FText FormattedText = FText::Format(NSLOCTEXT("GameUI", "DurabilityFormat", "{0}%"), Args);
			TextBlock_DurabilityValue->SetText(FormattedText);
		}
		else
		{
			HorizontalBox_Durability->SetVisibility(ESlateVisibility::Collapsed);
		}
	}
}

void UItemToolTipWidget::SetItemDurabilityColor()
{
	if(UInventoryUtilityLibrary::IsItemClassValid(ItemData))
	{
		
		FLinearColor FinalColor = ItemData.Durability > 10 ? TextGreenColor : TextRedColor;
		TextBlock_DurabilityText->SetColorAndOpacity(FinalColor);
		TextBlock_DurabilityValue->SetColorAndOpacity(FinalColor);
	}
}

void UItemToolTipWidget::UpdateItemStatsComparison(UItemToolTipWidget* InComparedToolTip)
{
	TArray<FString> Keys;
	StatWidgets.GenerateKeyArray(Keys);
	
	if(InComparedToolTip)
	{
		for(const auto& Key : Keys)
		{
			UItemStatsSlotWidget* ComparedStatsSlotWidget = InComparedToolTip->StatWidgets[Key];
			UItemStatsSlotWidget* StatsSlotWidget = StatWidgets[Key];
			if(ComparedStatsSlotWidget)
			{
				StatsSlotWidget->ShowComparisonToolTip(ComparedStatsSlotWidget->StatValue);
			}
			else
			{
				StatsSlotWidget->ShowComparisonToolTip(0.f);
			}
		}
	}
	else
	{
		for(const auto& Key : Keys)
		{
			StatWidgets[Key]->HideComparisonToolTip();
		}
	}
}

void UItemToolTipWidget::SetAlreadyReadVisibility()
{
	if(UInventoryUtilityLibrary::IsItemClassValid(ItemData))
	{
		UItemBase* ItemBase = ItemData.ItemClass.GetDefaultObject();
		const bool IsVisible = ItemBase->UseType == EItemUseType::TextDocument && ItemData.AlreadyUsed;
		TextBlock_AlreadyRead->SetVisibility(IsVisible ? ESlateVisibility::SelfHitTestInvisible : ESlateVisibility::Collapsed);
	}
}
